import turtle as trtl

painter = trtl.Turtle()

painter.penup()
painter.goto(-50,-50)
painter.pendown()
painter.forward(100)
painter.left(90)
painter.forward(100)
painter.left(90)
painter.forward(100)
painter.left(90)
painter.forward(100)
painter.penup()
painter.goto(50,50)
painter.pendown()
painter.left(215)
painter.forward(85)
painter.left(109)
painter.forward(87)
